# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # SplitKB.com Aurora (Corne)
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: aurora_corne_central_left
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_right
    artifact-name: aurora_corne_peripheral_right
  # Chocofi (with cirque trackpad)
  - board: nice_nano_v2
    shield: choco_cirque_left nice_view_adapter nice_view
    #shield: corne_left nice_view_adapter nice_view cirque_pinnacle_central
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: choco_cirque_central_left
  - board: nice_nano_v2
    shield: choco_cirque_left nice_view_adapter nice_view
    #shield: corne_left nice_view_adapter nice_view cirque_pinnacle_central
    snippet: zmk-usb-logging
    artifact-name: choco_cirque_central_left_DEBUG
  - board: nice_nano_v2
    shield: choco_cirque_right
    #shield: corne_right cirque_pinnacle_adapter cirque_pinnacle_trackpad
    artifact-name: choco_cirque_peripheral_right
  # Settings_reset
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset
